apiVersion: v1
kind: Pod
metadata:
  name: init-container-demo 
  labels: 
    app: init-container
spec:
  initContainers:
  - name: init-config 
    image: busybox:1.36
    command:
      - sh
      - -c
      - |
        echo "Initializing application..."
        echo "APP_ENV=production" > /shared/config.env
        echo "Initialization completed."
    volumeMounts:
    - name: shared-volume 
      mountPath: /shared
  containers: 
  - name: app
    image: busybox:1.36 
    command:
      - sh
      - -c
      - |
        echo "Main Application Started"
        echo "Configuration"
        cat /shared/config.env
        sleep 3600
    volumeMounts:
    - name: shared-volume 
      mountPath: /shared
  
  volumes:
  - name: shared-volume
