---
apiVersion: v1 
kind: Pod 
metadata:
  name: burstable-pod
  labels:
    app: frotnend
spec:
  containers:
  - name: nginx-container
    image: nginx:1.27-alpine
    ports:
    - containerPort: 80 

    resources:
      requests:
        cpu: "250m"
        memory: "216Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

---
apiVersion: v1 
kind: Pod 
metadata:
  name: guranteed-pod
  labels:
    app: frotnend
spec:
  containers:
  - name: nginx-container
    image: nginx:1.27-alpine
    ports:
    - containerPort: 80 

    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"


---
apiVersion: v1 
kind: Pod 
metadata:
  name: besteffort-pod
  labels:
    app: frotnend
spec:
  containers:
  - name: nginx-container
    image: nginx:1.27-alpine
    ports:
    - containerPort: 80 
