apiVersion: v1
kind: Pod
metadata:
  name: nginx
  annotations:
    description: "Nginx web server"
    owner: "platform-team"
spec:
  containers:
    - name: nginx
      image: nginx:1.27
      ports:
      - containerPort: 80